### PR TITLE
Fix to make compatible with emmeans version 1.10.4

### PR DESCRIPTION
**Pull request by rvlenth**
# Pull Request

This PR updates the code for `lsmeans()` so that it is compatible with **emmeans** version 1.10.4 and later. See issue #67.
The change to **emmeans** was needed so that `geeglm` objects are handled the same way as `glmgee` objects as far as degrees of freedom are concerned. Now we have finite d.f. for both classes.

### CODE REVIEW

**Comment by rvlenth** [comment]
PS you will need to install **emmeans** from Github first, so that you have the up-to-date version.

**Comment by shajoezhu** [comment]
Dear professor @rvlenth , I guess you are planning to make a new cran release for emmeans, and there is a breaking change at the moment? Many thanks for raising this PR. 

we could add 

`Remotes: rvlenth/emmeans` to the description for now for testing. 

Internally, we use a tool called staged.dependencies. https://github.com/openpharma/staged.dependencies to manage dependencies between packages for development. 

I was wondering if you were going to create releases, and tags at https://github.com/rvlenth/emmeans remote, that might be easier for us to manage, and keep track of these changes. Thanks!

**Comment by shajoezhu** [comment]
I can confim this builds fine with the new version

image

We could wait once emmeans is cran released, rerun the pipeline, and merge it. Thanks @rvlenth for the fixes.

**Comment by shajoezhu** [comment]
TODO:

@shajoezhu @rvlenth 

update description once emmeans cran released to 1.10.4

**Comment by shajoezhu** [comment]
will follow up in https://github.com/insightsengineering/tern.gee/pull/70

**Pull request closed without merging**
